select_a_record= "//div[@class='ag-center-cols-container']"
enterprise_name= "(//span[@class='text-11 grey-60']//following-sibling::span[@class='text-13' ])[2]"
add_user="//button[@class='dropdown-item text-13 p-dropdown-menu-items' and contains(text(),' Add User ')]"
checkbox1= "(//input[@class='mr-12'])[1]"
checkbox2= "(//input[@class='mr-12'])[2]"
save_button= "//div[@class='d-flex justify-content-center align-items-center text-14 p-2rx headerBar ml-1 next-button next-button enabledButton']"
search_existing_enterprise="//input[@placeholder='Search Enterprises']"
logout_icon = "//img[@src='/Images/logout.svg']"
logout_button = "//button[@class='submitbtn confirmButton text-14 submitbtnEnabled font-weight-bolder']"
