# Add Account Holder (Primary User)
new_primary_user_radio = "//input[@id='newuser']"
existing_user_radio = "//input[@id='existinguser']"
user_first_name_field = "//input[@placeholder='Enter first name']"
user_last_name_field = "//input[@placeholder='Enter last name']"
user_name_field = "//input[@placeholder='Enter user name']"
phone_number_field = "//input[@id='myInput']"
user_email_field = "//input[@placeholder='Enter email address']"
auto_generate_password_checkbox = "(//input[@name='registeredaddress'])[1]"
require_password_change_checkbox = "(//input[@name='registeredaddress'])[2]"
user_password_field = "//input[@placeholder='Enter password']"
confirm_password = "//input[@placeholder='Enter confirm password']"
select_user_field = "//input[@placeholder='Type in a name to search']"

Password_policy_error="//span[@class='error' and @title='PasswordPolicy Error.']"
