
remove_instance_header = "//span[@class='text-20' and text()='Remove Instance']"
remove_instance_icon_row_1 = "//div[@class='d-flex justify-content-center align-items-center h-100']/img[@name='deleteInstance']"
remove_instance_button = "//button[@class='submitbtn confirmButton text-14 submitbtnEnabled font-weight-bolder w-10r']//following:: span"
instance_summary_header_field = "//h5[@class='m-0' and text()='Instance Summary']"
instance_details_application_name = "(//span[@class='text-11 grey-60']//following-sibling::span)[1]"
instance_details_env_name = "(//span[@class='text-11 grey-60']//following-sibling::span)[2]"
instance_details_url = "(//div[@class='d-flex flex-column col-6 detail-display']//span[2])[5]"
goappps_instances_header_field = "//div[@class='d-flex justify-content-between align-items-center headerBar']//span[contains(text(),'GoApps Instances')]"
goappps_instances_search_field = "//input[@placeholder='Search Instances']"
element_in_application_column = "(//div[@class='d-flex align align-items-center']//span)"
edit_instance_details = "//button[@class='dropdown-item text-13 p-dropdown-menu-items'][contains(text(),'Edit Details')]"
edit_auth_button = "//button[contains(text(),'Edit Auth')]"
edit_instance_details_header_field= "//span[@class='text-20' and text()='Edit Instance Details']"
goapps_instance_count="//span[@class='ag-paging-row-summary-panel-number'and @id='ag-888-row-count']"
#edit instance details
instance_name = "//input[@placeholder='Enter name for the new instance']"
instance_env = "//select[@name='env' and @placeholder='Select']"
instance_env_dropdown_element = "//select[@name='env' and @placeholder='Select']//option"
edit_instance_url = "//label[contains(text(),'Instance URL')]//following-sibling::input"
instance_ref_ent_identifier = "//label[contains(text(),'Reference Enterprise Identifier')]//following-sibling::input"
update_instance_button = "//button[@class='submitbtn confirmButton text-14 submitbtnEnabled font-weight-bolder']"
cancel_button = "//div[@class='p-3 margin-secondary text-14 d-flex justify-content-center align-items-center blue-60 p-2rx cursor-pointer font-weight-bolder']"
reference_id="//span[@class='text-11 grey-60' and text()='Reference Id']//following-sibling::span[@class='text-13']"
#options
generate_api_key= "//button[contains(text(),'Generate API Key')]"
popup_message = "(//div[@class='Vue-Toastification__toast-component-body']//descendant::span)[1]"
api_key = "(//div[@class='Vue-Toastification__toast-component-body']//descendant::span)[3]"
close_popup = "//button[@class='Vue-Toastification__close-button']"

#edit auth
whitelisted_ips_input_field = "//label[contains(text(),'Whitelisted Ips')]//following::input[1]"
redirect_url_input_field = "//label[contains(text(),'Redirect URL')]//following::input"

goapps_instance_icon = "//img[@src='/Images/goapps.svg']"
element_in_environment_column = "//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//descendant::div[@aria-colindex='2']"
element_in_instance_url_column= "//div[@class='ag-body-viewport ag-layout-normal ag-row-no-animation']//descendant::div[@aria-colindex='3']"
logout_icon = "//img[@src='/Images/logout.svg']"
confirm_logout_button = "//button[@class='submitbtn confirmButton text-14 submitbtnEnabled font-weight-bolder']"
login_page_header_field = "//h1[@class='login']"
cancel_logout_button="//div[@class='p-3 margin-secondary text-14 d-flex justify-content-center align-items-center blue-60 p-2rx cursor-pointer font-weight-bolder']"